
// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: true,
  srvTCC: 'https://tcc-srv-fio-navalha-lcflbvjtra-uc.a.run.app',
  API_CEP: 'https://viacep.com.br/ws/'
};

