
// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: false,
  srvTCC: 'http://localhost:8080',
  API_CEP: 'https://viacep.com.br/ws/'
};

