export const environmentExternalLinks = {
  production: true,
  LOGO_ICON_PNG: '../assets/icons/Logo521.svg',
  ICONE_BARBEARIA_CADASTRO_WHITE: '../assets/icons/icones-free/barber-icon-white.png',
  ICONE_CLIENTE_VAREJO_CADASTRO_WHITE: '../assets/icons/icones-free/beard-icon-white.png',
  ICONE_UPLOAD_FOTO_PERFIL: '../assets/images/foto-perfil-default.png',
  ICONE_CAMERA_UPLOAD_FOTO_PERFIL: '../assets/icons/icon-camera.png',
  ICONE_SETA_PRA_BAIXO: '../assets/icons/seta-para-baixo.png',
  ICONE_CANCELAMENTO_PEDIDO: '../assets/icons/cancel-icon.png',
  ICONE_APROVACAO_PEDIDO: '../assets/icons/aprove-icon.png',
  ICONE_SEARCH_WHITE: '../assets/icons/icones-free/search-icon-white.png',
  FOTO_BARBEARIA: '../assets/icons/icones-free/barbearia_icone_exemplo.jpg',
  ICONE_FAVORITO_VAZIA: '../assets/icons/icones-free/star-empty.svg',
  ICONE_FAVORITO_METADE: '../assets/icons/icones-free/star-half-fill.svg',
  ICONE_FAVORITO_PREENCHIDA: '../assets/icons/icones-free/star-complete-fill.svg',
};
