# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: application

on:
  push:
    branches: [ main, release/esteira, develop ]
  pull_request:
    branches: [ main, release/esteira, develop ]

jobs:
  build:
    name: Build e Testes
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Abrindo projeto
    - run: cd /home/runner/work/tcc-fed-fio-navalha/tcc-fed-fio-navalha
    - name: Install dependencies
    - run: npm ci
    - name: Buildando aplicacao
    - run: npm run build --prod
    - name: Rodando os testes unitarios
    - run: npm run test
